// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN6IxYLiWMsReOMtJs6lL31waxZZPK3RA',
    appId: '1:593772239726:web:a08dc5de63e492aa10bf7f',
    messagingSenderId: '593772239726',
    projectId: 'writereadlearn-3',
    authDomain: 'writereadlearn-3.firebaseapp.com',
    storageBucket: 'writereadlearn-3.appspot.com',
    measurementId: 'G-4PHV4JNFD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw7D_qfK0UrCEDiyuhbPyQPXmR0siaQwk',
    appId: '1:593772239726:android:dc2e1d028d06030e10bf7f',
    messagingSenderId: '593772239726',
    projectId: 'writereadlearn-3',
    storageBucket: 'writereadlearn-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyUooqlNHmEuZPa9TJ5RKHuxVmOGrTbM4',
    appId: '1:593772239726:ios:ecd221a1e7a6b1aa10bf7f',
    messagingSenderId: '593772239726',
    projectId: 'writereadlearn-3',
    storageBucket: 'writereadlearn-3.appspot.com',
    iosBundleId: 'com.example.wrl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyUooqlNHmEuZPa9TJ5RKHuxVmOGrTbM4',
    appId: '1:593772239726:ios:ecd221a1e7a6b1aa10bf7f',
    messagingSenderId: '593772239726',
    projectId: 'writereadlearn-3',
    storageBucket: 'writereadlearn-3.appspot.com',
    iosBundleId: 'com.example.wrl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN6IxYLiWMsReOMtJs6lL31waxZZPK3RA',
    appId: '1:593772239726:web:5fcf686f729a954610bf7f',
    messagingSenderId: '593772239726',
    projectId: 'writereadlearn-3',
    authDomain: 'writereadlearn-3.firebaseapp.com',
    storageBucket: 'writereadlearn-3.appspot.com',
    measurementId: 'G-4Z720NB8ER',
  );

}