// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdfWExvfsIMcgws3xa42kxAcdWcmmAfvA',
    appId: '1:806856531371:web:649fb86dea7f9a0ea986ee',
    messagingSenderId: '806856531371',
    projectId: 'writereadlearn-2',
    authDomain: 'writereadlearn-2.firebaseapp.com',
    storageBucket: 'writereadlearn-2.appspot.com',
    measurementId: 'G-H5C9GVYF1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqzE2igeBHU_Diyz77DHbFHVU09r2Obx4',
    appId: '1:806856531371:android:0707d3133051eb0ba986ee',
    messagingSenderId: '806856531371',
    projectId: 'writereadlearn-2',
    storageBucket: 'writereadlearn-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuLz8iuRGhUpbd7X89u98jnCTaRVQF0r4',
    appId: '1:806856531371:ios:e409049f4e6d2042a986ee',
    messagingSenderId: '806856531371',
    projectId: 'writereadlearn-2',
    storageBucket: 'writereadlearn-2.appspot.com',
    iosBundleId: 'com.example.wrl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuLz8iuRGhUpbd7X89u98jnCTaRVQF0r4',
    appId: '1:806856531371:ios:e409049f4e6d2042a986ee',
    messagingSenderId: '806856531371',
    projectId: 'writereadlearn-2',
    storageBucket: 'writereadlearn-2.appspot.com',
    iosBundleId: 'com.example.wrl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdfWExvfsIMcgws3xa42kxAcdWcmmAfvA',
    appId: '1:806856531371:web:62c54e26bb095132a986ee',
    messagingSenderId: '806856531371',
    projectId: 'writereadlearn-2',
    authDomain: 'writereadlearn-2.firebaseapp.com',
    storageBucket: 'writereadlearn-2.appspot.com',
    measurementId: 'G-KT3LRVQCTS',
  );
}
